# Numpy Tutorial

In [14]:
import numpy as np


In [15]:
np.array([1,5])

array([1, 5])

In [16]:
a=np.array([2,6,9],dtype='int16')

In [17]:
print(a)


[2 6 9]


In [18]:
a.ndim


1

In [19]:
a.shape

(3,)

In [20]:
a.dtype

dtype('int16')

In [21]:
b=np.array([1.0,2.2,3.3],[8.2,9.0,3.4])

TypeError: Field elements must be 2- or 3-tuples, got '8.2'

In [23]:
b=np.array([1.0,2.2,3.3],[8.0,9.0,3.4])

TypeError: Field elements must be 2- or 3-tuples, got '8.0'

In [24]:
b=np.array([[1.0,2.2,3.3],[8.4,9.0,3.4]])

In [25]:
print(b)

[[1.  2.2 3.3]
 [8.4 9.  3.4]]


In [ ]:
b.ndim

In [ ]:
b.dtype

In [ ]:
a.itemsize

In [ ]:
b.itemsize

In [ ]:
#get size
a.itemsize


In [27]:
#get size
b.itemsize

8

## accessing/changing specific elements,rows,columns etc

In [29]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [31]:
print (a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [32]:
a.itemsize

4

In [33]:
a.ndim

2

In [34]:
a.shape  #it gives row index and column index#

(2, 7)

In [35]:
a[1,2]  #get a specific element 

10

In [36]:
a[0,1]

2

In [37]:
a[1,:] #to get a specific row  ,

array([ 8,  9, 10, 11, 12, 13, 14])

In [38]:
a[:,0] #to get a specific column

array([1, 8])

In [39]:
a[0,1:6:2]   #[startindex:endindex:stepsize], in order to slice .

array([2, 4, 6])

In [40]:
a[0,2:7:1]

array([3, 4, 5, 6, 7])

In [41]:
a[0,2::1]

array([3, 4, 5, 6, 7])

In [42]:
a[0,2:7:]

array([3, 4, 5, 6, 7])

## Initaializing diffrent types of arrays

In [46]:
np.zeros([2,3])


array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones([45,56])

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [51]:
np.ones([2,2],dtype='int32')

array([[1, 1],
       [1, 1]])

In [59]:
w=np.ones([2,2],dtype='int16')
print(w)

[[1 1]
 [1 1]]


In [60]:
w.dtype

dtype('int16')

## any other number

In [63]:
np.full([2,2],99)

array([[99, 99],
       [99, 99]])

In [62]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [64]:
np.full([2,2],99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

## full and full_like

In [65]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [66]:
a.shape

(2, 7)

In [69]:
np.full(a.shape,99)    # using full

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [70]:
np.full_like(a,99)    # using full_like

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

## random decimal numbers

In [71]:
np.random.rand(2,3)

array([[0.22080148, 0.27951459, 0.62329636],
       [0.56296684, 0.934423  , 0.20415979]])

In [75]:
a.shape


(2, 7)

In [74]:
np.random.random_sample(a.shape)

array([[0.4977036 , 0.33194334, 0.51302766, 0.37459969, 0.51499372,
        0.80408007, 0.49034504],
       [0.86707414, 0.77152443, 0.13582396, 0.71778231, 0.69821055,
        0.64255721, 0.15083119]])

## random integer values

In [76]:
np.random.randint([2,3])

array([1, 2])

In [85]:
np.random.randint(8,size=(2,3))

array([[2, 2, 1],
       [6, 4, 1]])

In [92]:
a.shape

(2, 3)

In [93]:
a.size

6

In [91]:
print(a)

[[1 2 3]
 [4 5 6]]


In [90]:
a=np.array([[1,2,3],[4,5,6]])

## identity matrix

In [94]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [95]:
# REPEAT AN ARRAY !!

arr=np.array([[1,2,3]])
r = np.repeat(arr,3)
print(r)

[1 1 1 2 2 2 3 3 3]


In [102]:
r = np.repeat(arr,3,axis=0)
l= np.repeat(arr,3,axis=1)
print(r)
print(l)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


## make a [5,5] matrix with ones and fill the middle [3,3] matrix with zeroes .

In [109]:
o=np.ones([5,5],dtype='int32')
print(o)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [108]:
z=np.zeros([3,3],dtype='int32')
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [110]:
o[1,1]=z[1,1]

In [111]:
print(o)

[[1 1 1 1 1]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [115]:
o[1:4,1:4]=z
print(o)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## be careful while copying arrays

In [120]:
a=np.array([2,3])
print(a)

[2 3]


In [118]:
b=a
b[0]=100
print(b)

[100   3]


In [119]:
print(a)

[100   3]


### use  copy() function , to avoid this ,.

In [125]:
b=a.copy()
b[0]=12
print('b=',b)
print('a=',a)

b= [12  3]
a= [2 3]


## Mathematics

In [126]:
a+2

array([4, 5])

In [130]:
a*2

array([4, 6])

In [131]:
a+b

array([14,  6])

In [132]:
b/a

array([6., 1.])

In [133]:
b*a

array([24,  9])

In [136]:
a=np.array([[2,3],[4,5]])
print(a)

[[2 3]
 [4 5]]


In [137]:
b=np.array([[1,3],[4,1]])
b

array([[1, 3],
       [4, 1]])

In [138]:
a*b    #NORMAL MULTIPLICATION OF DIRECTLY INDEX .

array([[ 2,  9],
       [16,  5]])

In [141]:
np.matmul(a,b)  # MATRIX MULTIPLICATION

array([[14,  9],
       [24, 17]])

In [139]:
a*2


array([[ 4,  6],
       [ 8, 10]])

In [140]:
a**2

array([[ 4,  9],
       [16, 25]])

## Finding determinant

In [145]:
j=np.identity(3)
print(j)
np.linalg.det(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

# Statistics

In [147]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

### minimum of stats

In [154]:
np.min(stats)

1

### maximum of stats

In [197]:
np.max(stats ,axis=1)

array([3, 6])

### sum the stats

In [155]:
np.sum(stats)

21

## Reorganizing Arrays

### reshaping a given array

In [159]:
before = np.array([[2,3,4],[8,9,7]])
before
before.shape

(2, 3)

In [161]:
before.reshape((6,1))

array([[2],
       [3],
       [4],
       [8],
       [9],
       [7]])

In [162]:
before

array([[2, 3, 4],
       [8, 9, 7]])

## Vertically stacking arrays  (or) matrixs

In [166]:
v = np.array([[1,2,3],[4,5,6]])
v1=np.array([[7,8,9],[10,11,12]])
np.vstack([v,v1])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Horizontal stacking arrays (or) matrixs

In [168]:
v = np.array([[1,2,3],[4,5,6]])
v1=np.array([[7,8,9],[10,11,12]])
np.hstack([v,v1])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## loading data from files without using pandas but using numpy

In [183]:
np.genfromtxt('data.txt')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77., 78.,
       79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91.,
       92., 93., 94., 95., 96., 97., 98., 99.])

## Bollean masking and advanced indexing 

In [189]:
data>50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [198]:
data[data>8]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
       94, 95, 96, 97, 98, 99])

In [199]:
np.any(data>50,axis=0)

True

In [211]:
data= np.genfromtxt('data.txt')
data=data.astype('int32')

In [217]:
a.any((data>50 & data<100))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()